src/Entity/Contrat.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ContratRepository")
 */
class Contrat
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Description;

    /**
     * @ORM\Column(type="integer")
     */
    private $Reward;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\User", inversedBy="contrats")
     */
    private $User;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Type;

    public function __construct()
    {
        $this->User = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->Name;
    }

    public function setName(string $Name): self
    {
        $this->Name = $Name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }

    public function getReward(): ?int
    {
        return $this->Reward;
    }

    public function setReward(int $Reward): self
    {
        $this->Reward = $Reward;

        return $this;
    }

    /**
     * @return Collection|User[]
     */
    public function getUser(): Collection
    {
        return $this->User;
    }

    public function addUser(User $user): self
    {
        if (!$this->User->contains($user)) {
            $this->User[] = $user;
        }

        return $this;
    }

    public function removeUser(User $user): self
    {
        if ($this->User->contains($user)) {
            $this->User->removeElement($user);
        }

        return $this;
    }

    public function getType(): ?string
    {
        return $this->Type;
    }

    public function setType(string $Type): self
    {
        $this->Type = $Type;

        return $this;
    }
}

src/Entity/Marais.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\MaraisRepository")
 */
class Marais
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Marche", mappedBy="marais", orphanRemoval=true)
     */
    private $marche;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $marais;

    public function __construct()
    {
        $this->marche = new ArrayCollection();
    }

    public function __toString()
    {
        return $this->marais;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return Collection|Marche[]
     */
    public function getMarche(): Collection
    {
        return $this->marche;
    }

    public function addMarche(Marche $marche): self
    {
        if (!$this->marche->contains($marche)) {
            $this->marche[] = $marche;
            $marche->setMarais($this);
        }

        return $this;
    }

    public function removeMarche(Marche $marche): self
    {
        if ($this->marche->contains($marche)) {
            $this->marche->removeElement($marche);
            // set the owning side to null (unless already changed)
            if ($marche->getMarais() === $this) {
                $marche->setMarais(null);
            }
        }

        return $this;
    }

    public function getMarais(): ?string
    {
        return $this->marais;
    }

    public function setMarais(string $marais): self
    {
        $this->marais = $marais;

        return $this;
    }


}

src/Form/MaraisType.php
<?php

namespace App\Form;

use App\Entity\Marais;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class MaraisType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
        ->add('marais', TextType::class, [
            'label' => 'Nom du Marais',
        ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Marais::class,
        ]);
    }
}

src/Controller/MaraisController.php
<?php

namespace App\Controller;

use App\Entity\Marais;
use App\Form\MaraisType;
use App\Repository\MaraisRepository;
use App\Repository\MarcheRepository;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

class MaraisController extends AbstractController
{
    /**
     * @Route("/marais", name="marais")
     */
    public function index(MaraisRepository $repository)
    {
        $marais = $repository->findAll();

        return $this->render('marais/index.html.twig', [
            'controller_name' => 'MaraisController',
            'maraiss' => $marais,
        ]);
    }

    /**
     * @Route("/marais/{id}", name="marais_show")
     */
    public function show(MaraisRepository $repository , MarcheRepository $repository2 ,$id){
        $marais = $repository->find($id);
        $marches = $repository2->findBy(['marais' => $id]);
        return $this->render('marais/show.html.twig', [
            'marais' => $marais,
            'marches' => $marches
        ]);
    }


    /**
     * @param Request $request
     * @param ManagerRegistry $managerRegistry
     * @return \Symfony\Component\HttpFoundation\Response
     * @Route("/admin/create-marais",name="marais_create")
     */
    public function create(Request $request, ManagerRegistry $managerRegistry){
        $marais = new Marais();

        $form = $this->createForm(MaraisType::class, $marais);
        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()){
            $managerRegistry->getManager()->persist($marais);
            $managerRegistry->getManager()->flush();
            return $this->redirectToRoute('marais');
        }

        return $this->render('marais/create.html.twig',[
            'formMarais' => $form->createView()
        ]);
    }
}

templates/marais/create.html.twig
{% extends 'base.html.twig' %}

{% block title %}Créer ton marais haha ^^{% endblock %}

{% block body %}
    <style>
        .creation{
            margin-top: 50px;
        }
    </style>

    <section class="creation">
        <div>
            {{ form_start(formMarais) }}
            {{ form_row(formMarais.marais, {'attr' :{ 'placeholder' : 'le grarais...'}}) }}
            <button class="btn btn-success">Créer le marais</button>
            {{ form_end(formMarais) }}
        </div>

    </section>
{% endblock %}

templates/marais/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello Marais!{% endblock %}

{% block body %}
    <style>
        body {
            color:black;
            background-color:white;
            background-image:url({{ asset('img/geralt_de_la_rive.jpg') }});
            background-attachment:fixed;
            background-size: cover;
            background-repeat: no-repeat;
        }
    </style>
    <div class="col-6 offset-3">
        <div class="card mt-5 text-center"
             style="box-shadow: -1px 2px 2px black;
             background-color: tomato; font-size: 3em; color:black">
            <h1> Accéder aux marais </h1>
            <p style="font-size: 0.4em">Accéder à un marais permet d'y trouver tous ses marchés</p>
        </div>
    </div>
    {% for marais in maraiss %}
        <div class="col-6 offset-3">
            <a class="lien-marais" href={{ path('marais_show', { 'id': marais.id } ) }} >
            <div class="card mt-3 text-center"
                 style="box-shadow: -1px 2px 2px black; font-size: 3em;
                        background-color: forestgreen; color:black">
                {{ marais }}
            </div>
            </a>
        </div>
    {% endfor %}
{% endblock %}

templates/marais/show.html.twig
{% extends 'base.html.twig' %}
{% block title %}Marchés du marais {% endblock %}

{% block body %}
    <style>
        body{
            background-image:url({{ asset('img/geralt_de_la_rive.jpg') }});
            background-attachment:fixed;
            background-size: cover;
            background-repeat: no-repeat;
        }
    </style>

    {% for marche in marches %}
        <div class="col-6 offset-3">
            <a class="lien-marche" href={{ path('marche_show', { 'id': marche.id } ) }} >
                <div class="card mt-3 text-center"
                     style="box-shadow: -1px 2px 2px black;
                            background-color: forestgreen; font-size: 3em; color:black">
                    {{ marche }}
                    <p class="mt-n2" style="font-size: 0.4em"> {{ marche.description }}</p>
                </div>
            </a>
        </div>
    {% endfor %}

{% endblock %}